apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: cli-job-sa-role
  namespace: openshift-logging
rules:
  - apiGroups:
      - logging.openshift.io
    resources:
      - clusterloggings
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cli-job-sa-rolebinding
  namespace: openshift-logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cli-job-sa-role
subjects:
  - kind: ServiceAccount
    name: cli-job-sa
