apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: cli-job-sa-role
rules:
  - apiGroups:
      - logging.openshift.io
      - apiextensions.k8s.io
    resources:
      - clusterloggings
      - customresourcedefinitions
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cli-job-sa-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cli-job-sa-role
subjects:
  - kind: ServiceAccount
    name: cli-job-sa
