apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
