apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators-redhat
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    argocd.argoproj.io/hook: PreSync
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
