apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

bases:
- github.com/andre-mueller-de/openshift-cluster-config/cluster-config/config/overlays/default
- ../../../applications/base
- ../../../projects/base
